name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  run-rubocop:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: bundle
      - run: rubocop

  build-ruby:
    needs: run-rubocop
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version: [3.0.3]
    steps:
      - uses: actions/checkout@v2

      - name: Build Ruby ${{ matrix.ruby-version }}
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}

  multiverse:
    needs: build-ruby
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
        options: >-
          --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        multiverse: ["frameworks;rails;rest"]
        ruby-version: [3.0.3]

    steps:
      - uses: actions/checkout@v2

      - name: Build Ruby ${{ matrix.ruby-version }}
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Test MySQL
        run: mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"

      - name: Run Multiverse Tests
        uses: nick-invision/retry@v1.0.0
        with:
          timeout_minutes: 60
          max_attempts: 1
          command:  bundle exec rake test:multiverse[active_record_pg,verbose]
        env:
          DB_PASSWORD: root
          MYSQL_PASSWORD: root
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_HOST: 127.0.0.1
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password

      - name: Annotate errors
        if: ${{ failure() }}
        uses: ./.github/actions/annotate
